/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { MovieType, PostType, RandomUser } from '../models'

const Home: NextPage = () => {
  const [data, setData] = useState([])
  const [user, setUser] = useState({} as RandomUser)
  const [movies, setMovies] = useState({} as MovieType)

  useEffect(() => {
    fetch('https://jsonplaceholder.typicode.com/posts')
    .then(response => response.json())
    .then(json => {
      setData(json)
    })
  }, [])


  // implement context so random user generated same as in navbar
  useEffect(() => {
    fetch(`https://randomuser.me/api`)
    .then(response => response.json())
    .then(json => {
      console.log("user fetched");
      console.log(json);
      
      setUser(json)
    })
  }, [])

  //implement context so that my favorite movies same in navbar
  const getMovieDetail = async () => {
    const url = `http://www.omdbapi.com/?i=tt1877830&apikey=64fee452`

    const response = await fetch(url);
    const responseJson = await response.json();

    if (responseJson) {
      setMovies(responseJson);
    } 
  }
  useEffect(() => {
    getMovieDetail()
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-5 flex flex-col gap-5">
        <div>
          <p>Hello, {user.results?.length > 0 && user.results[0]?.name?.first}</p>
        </div>
        <div>
          <h1>My Favorite Movies:</h1>
          {movies && <div>
            <img src={movies.Poster} height="120" width="120" alt="poster" />
          </div>}
        </div>
        <div className="flex flex-col gap-4">
          {data && data.map((d: PostType, index: number)=>{
            return (
              <a key={index} className="cursor-pointer">
                <div  className="rounded-lg bg-blue-400 p-5">
                <Link href={`/post/${d.id}`}>
                  <div>
                    <p>Title: {d.title}</p>
                    <p>Body: {d.body}</p>
                  </div>
                </Link>
              </div>
              </a>
            )
          })}
        </div>
      </main>
    </div>
  )
}

export default Home
